# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a13ce9a54cf22603ab5cff22a9f9597467ce534ee16c6e0bb63268ced0bec4cfad1c422d5bacb0c6008f6994496dc003e93657a1ff0a27514998d3e1025a9a6

test:
  secret_key_base: 982b1769cda003472adb6f62dda013c4a31f0b2d135282db697c8dd318c26984c89087972bcb7c3f14a5839aca8bc1fc7c53e702eaf99eaa63712c352206533d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
